### PR TITLE
Polynomial linear regression

### PR DESCRIPTION
**Pull request by Kaneki-Ken-7**
Both issue for main branch

### CODE REVIEW

**Comment by anuragc2001** [comment]
@kpratik1929 if you merge several issues in one PR the leaderboard will count only one PR merged and will point you accordingly. If you can then please open three different PRs for three different issues. This will help you score more points. Just a tip from my side.

**Comment by A1zenSousuke** [comment]
Ok i'll do the changes

**Comment by A1zenSousuke** [comment]
I have done the changes .you can check it now.

**Review by anuragc2001 — APPROVED** [review]
Looks good now.

**Comment by anuragc2001** [comment]
@kpratik1929 you've already added the code of this PR in your previous PR. Therefere we're having a merge conflict but becawe you've resolved 2 issues, I'll be closing this PR and your points will be awarded to you based of the issues you;ve closed. Job well done.

**Pull request closed without merging**
