### PR TITLE
Added Ridge Classifier

### PR DESCRIPTION
**Pull request by Kaneki-Ken-7**
Added Ridge Classifier and tuned it for better accuracy.

### CODE REVIEW

**Comment by A1zenSousuke** [comment]
@KrishnenduDakshi2002 is this updated correctly?

**Comment by anuragc2001** [comment]
@kpratik1929 you've submitted two issues in one PR?

**Comment by A1zenSousuke** [comment]
@anuragc2001 I think I have to open new branch for r2 scores and revert the changes in next commit.

**Review by anuragc2001 — CHANGES_REQUESTED** [review]
@kpratik1929 the formatting is wrong. If you've already included the names of the Model then you can delete the rest of the names under your edit. Those will look blank and are of no use.

**Comment by anuragc2001** [comment]
@kpratik1929 I'd suggest you reset your repo to a previous point and then separately add the ridge classifier code open a PR and then edit the R2 score and again open another PR. I'm closing this PR.

**Comment by anuragc2001** [comment]
@kpratik1929 please update the requested changes.

**Comment by A1zenSousuke** [comment]
@anuragc2001 you can check it now whether its correct format?

**Review by anuragc2001 — APPROVED** [review]
Yes everything looks fine and updated.

**Comment by anuragc2001** [comment]
@kpratik1929 yes thank you. Everything looks fine. Thank you for your contribution through out the project.

**Pull request merged**
