### PR TITLE
Completed Classification Problem

### PR DESCRIPTION
**Pull request by muhammadanas0716**
The notebook under the Classification section, namely the **Cancer Prediction** has been completed successfully!## Linked Issue 

Closes: #issue number that will be closed through this PR

#3 

### Describe the changes you've made
I've added the Random Forest Algorithm for the Cancer Detection notebook.

Give a clear description of what modifications you have made
Added a new algorithm and did a little bit of EDA

## Type of change
Solved an **issue**

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
In Google Colab - everything works perfectly fine.

Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

### CODE REVIEW

**Review by KrishnenduDakshi2002 — CHANGES_REQUESTED** [review]
Hey nice work
can you improve the predictions by hyper parameter tuning or scaling ?
you can do a cross validation too

tn, fp, fn, tp = confusion_matrix(y_test,y_pred).ravel()
tn, fp, fn, tp

if you execute the above line, you see that the false negatives are bit high, that can be reduced.
for disease prediction false negative is very important(model is predicting cancerous as non-cancerous, that is not good)

**Comment by muhammadanas0716** [comment]
I have updated the file. Please have a look. Let me know if I should do some further changes!

**Review by KrishnenduDakshi2002 — CHANGES_REQUESTED** [review]
Yea it did improved but to be honest this is not an actual hyper parameter tuning.
you can do RandomizedSearchCV, or GridSearchCV
other library like optuna 
try scaling or cross validation
Take your time no hurry.
Like test different things.

**Comment by muhammadanas0716** [comment]
Okay! So what accuracy level should I reach in your opinion?

**Comment by KrishnenduDakshi2002** [comment]
> Okay! So what accuracy level should I reach in your opinion?

as you can see Naive Bayes did perform good, 
I did get 0 false negative.

I am just telling you should try those things also, it may improve the accuracy.

**Comment by muhammadanas0716** [comment]
Yep! I'll surely do some hyperparameter tuning! No worries! I'm here to learn and that is what I intend to do!

**Comment by anuragc2001** [comment]
@muhammadanas365 Please reopen this PR merging directly into the main branch. There's some issue with the automatic github PR tracking system hence for your PRs to be counted properly please push them into the main. I've deleted the dev branch.

**Comment by muhammadanas0716** [comment]
No problem. Once I'm done with the hyper parameter tuning I shall do as you said. Thanks for notifying!

**Pull request closed without merging**
