### PR TITLE
Added KNN classifier

### PR DESCRIPTION
**Pull request by RohanHBTU**
## Linked Issue 

Closes: #issue number that will be closed through this PR
issue #5 Add a KNN classifier
### Describe the changes you've made
Give a clear description what modifications you have made

I have added a KNN classifier. Additionally, accuracy, confusion matrix and f1 score has also been printed.
Hyperparameter tuning has also been done.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how have you verified the changes made

I have calculated the best score and best parameters and also has shown f1 score, accuracy and confusion matrix.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :: |:Screenshot (141):
 Original Screenshot | Updated Screenshot |

### CODE REVIEW

**Comment by KrishnenduDakshi2002** [comment]
is it possible to lower the fn counts? If you can, pls try that.

**Comment by RohanHBTU** [comment]
> is it possible to lower the fn counts? If you can, pls try that.

Ok...I will work on that

**Comment by RohanHBTU** [comment]
despite many efforts and tuning ... KNN classifier is not improving the fn count. So, please accept and merge this as final work

**Comment by KrishnenduDakshi2002** [comment]
> despite many efforts and tuning ... KNN classifier is not improving the fn count. So, please accept and merge this as final work

okay.

**Pull request merged**
