### PR TITLE
Ridge Classifier Added

### PR DESCRIPTION
**Pull request by Kaneki-Ken-7**
added ridge classifier and tuned it for better accuracy .

### CODE REVIEW

**Comment by anuragc2001** [comment]
@KrishnenduDakshi2002 if everything looks good and you've no issues with the PR, we may merge it.

**Comment by KrishnenduDakshi2002** [comment]
> @KrishnenduDakshi2002 if everything looks good and you've no issues with the PR, we may merge it.

as I merged another PR from another contributor
 @kpratik1929  's PR is one commit behind.
Can you create another PR with updated branch.

**Comment by A1zenSousuke** [comment]
@KrishnenduDakshi2002 is it updated now?

**Comment by KrishnenduDakshi2002** [comment]
> @KrishnenduDakshi2002 is it updated now?

yes, you can go ahead.

**Comment by A1zenSousuke** [comment]
@KrishnenduDakshi2002 do i have to create new PR or this one will do?

**Comment by KrishnenduDakshi2002** [comment]
pls create a new PR.

**Comment by KrishnenduDakshi2002** [comment]
@kpratik1929 
pls create a new PR, that would be nice.

**Comment by anuragc2001** [comment]
@kpratik1929 we are going with this PR. We'll let you know if there are changes you need to make.

**Pull request closed without merging**
