### PR TITLE
Updated Cancer Prediction

### PR DESCRIPTION
**Pull request by muhammadanas0716**
## Linked Issue 
#3 

### Describe the changes you've made
Updated Cancer Prediction Notebook

Give a clear description of what modifications you have made
Did some hyper parameter tuning - GridSearchCV

## Type of change
Better change!

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
Google Colab

Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

### CODE REVIEW

**Review by KrishnenduDakshi2002 — CHANGES_REQUESTED** [review]
hi
I think you pushed the wrong notebook, it is the same notebook from you first commit where
you solved 4 issues.
I am looking forward to your commit.

**Comment by muhammadanas0716** [comment]
My bad, fixed now!

**Review by KrishnenduDakshi2002 — APPROVED** [review]
Nice job!!
See accuracy did improved.
Thanks for contributing in this issue.

**Comment by muhammadanas0716** [comment]
Did I get myself merged!?

**Comment by KrishnenduDakshi2002** [comment]
> Did I get myself merged!?

No.
Although you can't merge until unless maintainers wanted to do so.

Now you can comment any other issues if you want to.

**Comment by anuragc2001** [comment]
@muhammadanas365 Well done! Please start solving the remaining issues.

**Comment by muhammadanas0716** [comment]
Shall do! Do I become a member of your organization? Any perks? Nonetheless, I'll keep contributing!

**Comment by muhammadanas0716** [comment]
@anuragc2001 Any updates on my question?

**Pull request merged**
